Assignment.PresentationLayer/Controllers/DepartmentsController.cs
namespace PresentationLayer.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DepartmentsController : Controller
    {

        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;

        public DepartmentsController( IMapper mapper, IUnitOfWork unitOfWork)
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            // Retrieve All Departments
            var departments =await  _unitOfWork.Departments.GetAllAsync();
            var departmentViewModel = _mapper.Map<IEnumerable<Department>, IEnumerable<DepartmentViewModel>>(departments);

            return View(departments);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> CreateAsync(DepartmentViewModel departmentVM) 
        {
            //server side validation
            if (! ModelState.IsValid) return View(departmentVM);
            var department = _mapper.Map<DepartmentViewModel, Department>(departmentVM);

            await _unitOfWork.Departments.AddAsync(department);
            await _unitOfWork.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id) => await DepartmentControllerHandler(id, nameof(Details));
        public async Task<IActionResult> Edit(int? id) => await DepartmentControllerHandler(id, nameof(Edit));

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAsync([FromRoute]int id, DepartmentViewModel departmentVM)
        {
            if (id != departmentVM.Id) return BadRequest();

            if (!ModelState.IsValid) return View(departmentVM);

            try
            {
                var department = _mapper.Map<DepartmentViewModel, Department>(departmentVM);

                _unitOfWork.Departments.Update(department);

                if (await _unitOfWork.SaveChangesAsync() > 0)
                    TempData["Message"] = "Employee Updated Successfuly";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                // log Exception
                ModelState.AddModelError("", ex.Message);
            }
            return View(departmentVM);
        }

        public async Task<IActionResult> Delete(int? id) => await DepartmentControllerHandler(id,nameof(Delete));

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {

            if (!id.HasValue) return BadRequest();

            var department = await _unitOfWork.Departments.GetAsync(id.Value);

            if (department is null) return NotFound();

            try
            {
                _unitOfWork.Departments.Delete(department);
                await _unitOfWork.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return View(department);
            }
        }

        private async Task<IActionResult> DepartmentControllerHandler(int? id , string viewName)
        {

            if (!id.HasValue) return BadRequest();

            var department = await _unitOfWork.Departments.GetAsync(id.Value);

            if (department is null) return NotFound();
            var departmentVM = _mapper.Map<DepartmentViewModel>(department);


            return View(viewName, department);
        }
    }
}

Assignment.PresentationLayer/Controllers/EmployeesController.cs
namespace PresentationLayer.Controllers
{
    [Authorize(Roles ="Admin")]
    public class EmployeesController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;
        public EmployeesController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index(string? searchValue)
        {
            var employees = Enumerable.Empty<Employee>();

            if (string.IsNullOrWhiteSpace(searchValue))
                 employees = await _unitOfWork.Employees.GetAllWithDepartmentAsync();

            else employees = await _unitOfWork.Employees.GetAllAsync(searchValue);

            var employeeViewModel = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employees);

            return View(employeeViewModel);
        }

        public async Task<IActionResult> Create()
        {
            var employees = await _unitOfWork.Departments.GetAllAsync();
            SelectList listItems = new SelectList(employees, "Id", "Name");
            ViewBag.Departments = listItems;
            return View();
        }

        [HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(EmployeeViewModel employeeVM)
        {

            if (!ModelState.IsValid) return View(employeeVM);

            if (employeeVM.Image is not null)
                employeeVM.ImageName = await DocumentSittings.UploadFileAsync(employeeVM.Image , "Images");
           

            var employee = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
            await _unitOfWork.Employees.AddAsync(employee);
            await _unitOfWork.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id) => await EmployeeControllerHandler(id, nameof(Details));
        public Task<IActionResult> Edit(int? id) => EmployeeControllerHandler(id, nameof(Edit));

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, EmployeeViewModel employeeVM)
        {
            if (id != employeeVM.Id) return BadRequest();

            if (!ModelState.IsValid) return View(employeeVM);

            try
            {
                if (employeeVM.Image is not null)
                    employeeVM.ImageName = await DocumentSittings.UploadFileAsync(employeeVM.Image, "images");

                var employee = _mapper.Map<EmployeeViewModel,Employee>(employeeVM);

                _unitOfWork.Employees.Update(employee);

                if (await _unitOfWork.SaveChangesAsync() > 0)
                    TempData["Message"] = "Employee Updated Successfuly";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(employeeVM);
        }

        public async Task<IActionResult> Delete(int? id) => await EmployeeControllerHandler(id, nameof(Delete));

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {

            if (!id.HasValue) return BadRequest();

            var employee = await _unitOfWork.Employees.GetAsync(id.Value);

            if (employee is null) return NotFound();

            try
            {
                _unitOfWork.Employees.Delete(employee);
                if (await _unitOfWork.SaveChangesAsync() > 0 && employee.ImageName is not null)
                {
                    DocumentSittings.DeleteFile("Images" , employee.ImageName);
                }
                

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return View(employee);
            }
        }

        private async Task<IActionResult> EmployeeControllerHandler(int? id, string viewName)
        {

            if(viewName == nameof(Edit))
            {

                var departments = await _unitOfWork.Departments.GetAllAsync();
                SelectList listItems = new SelectList(departments, "Id", "Name");
                ViewBag.Departments = listItems;

            }
            if (!id.HasValue) return BadRequest();

            var employee = await _unitOfWork.Employees.GetAsync(id.Value);

            if (employee is null) return NotFound();

            var employeeVM = _mapper.Map<EmployeeViewModel>(employee);

            return View(viewName, employeeVM);
        }
    }
}

Assignment.PresentationLayer/Controllers/RoleController.cs
using System.Data;

namespace PresentationLayer.Controllers
{
    public class RoleController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if(!ModelState.IsValid) return View(model);

            var role = new IdentityRole
            {
                Name = model.Name
            };
            var result = await _roleManager.CreateAsync(role);
            if (result.Succeeded) return RedirectToAction(nameof(Index));

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(model);
        }

        public async Task<IActionResult> Index(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                var roles = await _roleManager.Roles.Select(r => new RoleViewModel
                {
                    Name = r.Name,
                    Id = r.Id
                }).ToListAsync();
                return View(roles);
            }
            var role = await _roleManager.FindByNameAsync(name);

            if (role is null) return View(Enumerable.Empty<RoleViewModel>());

            var model = new RoleViewModel
            {
                Name = role.Name,
                Id = role.Id
            };

            return View(model);
        }

        public async Task<IActionResult> Details(string id, string viewName = nameof(Details))
        {
            if (string.IsNullOrWhiteSpace(id)) return BadRequest();

            var role = await _roleManager.FindByIdAsync(id);
            if (role is null) return NotFound();

            var model = new RoleViewModel
            {
                Name = role.Name,
                Id = role.Id
            };

            return View(viewName, model);
        }

        public async Task<IActionResult> Edit(string id) => await Details(id, nameof(Edit));

        [HttpPost]
        public async Task<IActionResult> Edit(string id, RoleViewModel model)
        {
            if (id != model.Id) return BadRequest();
            if (!ModelState.IsValid) return View(model);

            try
            {
                var role = await _roleManager.FindByIdAsync(model.Id);
                if (role is null) return NotFound();
                role.Name = model.Name;

                await _roleManager.UpdateAsync(role);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(string id) => await Details(id, nameof(Delete));

        [ActionName("Delete")]
        [HttpPost]
        public async Task<IActionResult> ConfirmDelete(string id)
        {
            try
            {
                var role = await _roleManager.FindByIdAsync(id);
                if (role is null) return NotFound();
                await _roleManager.DeleteAsync(role);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View();

        }

        public async Task<IActionResult> AddOrRemoveUsers (string roleId)
        {
            var role = await _roleManager.FindByIdAsync (roleId);
            if (role is null) return NotFound();

            ViewBag.RoleId = roleId;

            var users = await _userManager.Users.ToListAsync();
            var usersInRole = new List<UserInRoleViewModel>();

            foreach (var user in users)
            {
                var userInRole = new UserInRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    IsInRole = await _userManager.IsInRoleAsync(user , role.Name)
                };

                usersInRole.Add(userInRole);
            }

            return View(usersInRole);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId, List<UserInRoleViewModel> users)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null) return NotFound();

            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appUser = await _userManager.FindByIdAsync(user.UserId);
                    if (appUser is null) return NotFound();

                    if (user.IsInRole && !await _userManager.IsInRoleAsync(appUser, role.Name))
                        await _userManager.AddToRoleAsync(appUser, role.Name);

                    if (!user.IsInRole && await _userManager.IsInRoleAsync(appUser, role.Name))
                        await _userManager.RemoveFromRoleAsync(appUser, role.Name);
                }
                return RedirectToAction(nameof(Edit), new { id = roleId });
            }
            return View(users);
        }
    }
}

Assignment.PresentationLayer/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;

namespace PresentationLayer.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;

		public UsersController(UserManager<ApplicationUser> userManager)
		{
			_userManager = userManager;
		}

		public async Task<IActionResult> Index(string email)
		{
			if (string.IsNullOrWhiteSpace(email))
			{
				var users = await _userManager.Users.Select(u => new UserViewModel
				{
					FirstName = u.FristName,
					LastName = u.LastName,
					UserName = u.UserName,
					Email = u.Email,
					Id = u.Id,
					Roles = _userManager.GetRolesAsync(u).GetAwaiter().GetResult()
				}).ToListAsync();
				return View(users);
			}
			var user = await _userManager.FindByEmailAsync(email);

			if (user is null) return View(Enumerable.Empty<UserViewModel>());

			var model = new UserViewModel 
			{
				FirstName = user.FristName,
				LastName = user.LastName,
				UserName = user.UserName,
				Email = user.Email ,
				Id = user.Id,
				Roles = await _userManager.GetRolesAsync(user)
			};

			return View(model);
		}

        public async Task<IActionResult> Details(string id, string viewName = nameof(Details))
        {
            if (string.IsNullOrWhiteSpace(id)) return BadRequest();

            var user = await _userManager.FindByIdAsync(id);
            if (user is null) return NotFound();

            var userModel = new UserViewModel
            {
                FirstName = user.FristName,
                LastName = user.LastName,
                UserName = user.UserName,
                Email = user.Email,
                Id = user.Id,
                Roles = await _userManager.GetRolesAsync(user)
            };

            return View(viewName,userModel);
        }

		public async Task<IActionResult> Edit(string id) => await Details(id , nameof(Edit));

		[HttpPost]
        public async Task<IActionResult> Edit(string id , UserViewModel model)
		{
			if(id != model.Id) return BadRequest();
			if (!ModelState.IsValid) return View(model);

			try
			{
				var user = await _userManager.FindByEmailAsync(model.Email);
				if (user is null) return NotFound();
				user.FristName = model.FirstName;
				user.LastName = model.LastName;
				await _userManager.UpdateAsync(user);

				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				ModelState.AddModelError(string.Empty, ex.Message);
			}
			return View(model);
		}

        public async Task<IActionResult> Delete(string id) => await Details(id , nameof(Delete));

		[ActionName("Delete")]
		[HttpPost]
        public async Task<IActionResult> ConfirmDelete(string id)
		{
            try
            {
                var user = await _userManager.FindByIdAsync(id);
                if (user is null) return NotFound();
                await _userManager.DeleteAsync(user);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View();

        }
    }
}

Assignment.PresentationLayer/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib SignUp Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/AuthStyleSheet.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative @ViewBag.Title Form</h1>

	@RenderBody();
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
<<<<<<< HEAD
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	@await RenderSectionAsync("Validation", required: false)

=======
>>>>>>> b22143d (Part 03 Auth Layout Setup)
	<!-- //main -->
</body>
</html>

Assignment.PresentationLayer/Views/Shared/_ButtonsPartial.cshtml
@model string

<td><a asp-action="Details" class="btn btn-warning" asp-route-id="@Model"><i class="fas fa-eye"></i>Details</a></td>
<td><a asp-action="Edit" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-edit"></i>Edit</a></td>
<td><a asp-action="Delete" class="btn btn-danger" asp-route-id="@Model"><i class="fas fa-trash"></i>Delete</a></td>

Assignment.PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment.PresentationLayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assignment.PresentationLayer.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-
        Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD Operation System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Departments" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Role" asp-action="Index">Roles</a>
                            </li>                            
                        }
                        @if (User.Identity.IsAuthenticated) // ==> True if Already loged in
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="SignOut">LogOut</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Assignment.PresentationLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Validation", required: false)
</body>
</html>